[pytest]
# 运行参数：显示详细信息，使用 allure 生成测试结果，控制控制台输出等
addopts = -vs --alluredir=outputs/reports/allure_results

# 测试用例所在的目录
testpaths = tests

# 测试用例文件命名规则
python_files = test_*.py

# 测试类命名规则
python_classes = Test*

# 测试函数命名规则
python_functions = test_*

# 注册自定义标记
markers =
    smoke: 冒烟测试
    login: 登录模块测试
    audit: 审核模块测试
    register: 注册模块测试
